name: Build PCF TimePicker Solution
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Power Platform CLI
        run: npm install -g pac

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build PCF control
        working-directory: TimePickerComponent
        run: |
          npm ci
          npm run build

      - name: Create and pack solution
        shell: pwsh
        run: |
          # 1) Create solution shell
          New-Item -ItemType Directory -Path WavsTimePicker.Sln -Force | Out-Null
          cd WavsTimePicker.Sln
          pac solution init --publisher-name WMATA --publisher-prefix wma --solution-name WavsTimePicker

          # 2) Add the PCF project reference
          pac solution add-reference ..\TimePickerComponent\TimePickerComponent.pcfproj

          # 3) Locate the cdsproj created by the CLI
          $proj = Get-ChildItem -Recurse -Filter *.cdsproj | Select-Object -First 1
          if (-not $proj) { throw "No .cdsproj found after 'pac solution init/add-reference'." }
          Write-Host "Building cdsproj: $($proj.FullName)"

          # 4) Build that exact cdsproj (restore + Release build)
          msbuild $proj.FullName /t:restore
          msbuild $proj.FullName /p:configuration=Release /v:m

          cd ..

          # 5) Collect any produced zips (Debug or Release)
          New-Item -ItemType Directory -Path output -Force | Out-Null
          $zips = Get-ChildItem -Path ".\WavsTimePicker.Sln" -Recurse -Filter *.zip
          if (-not $zips) {
            throw "No solution ZIPs were produced. Scroll up to the MSBuild step for the first error."
          }
          $zips | ForEach-Object { Copy-Item $_.FullName -Destination .\output\ }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: timepicker-solution-zips
          path: output/*.zip
