name: Build PCF TimePicker Solution
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Power Platform CLI
        run: npm install -g pac

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build PCF control
        working-directory: TimePickerComponent
        run: |
          npm ci
          npm run build

      - name: Pack solution
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path output -Force | Out-Null
          New-Item -ItemType Directory -Path WavsTimePicker.Sln -Force | Out-Null
          cd WavsTimePicker.Sln
          pac solution init --publisher-name WMATA --publisher-prefix wma --solution-name WavsTimePicker
          pac solution add-reference ..\TimePickerComponent\TimePickerComponent.pcfproj
          msbuild /t:restore
          msbuild /p:configuration=Release
          # Copy any zips from Debug or Release, wherever they land
          cd ..
          $zips = Get-ChildItem -Path ".\WavsTimePicker.Sln" -Recurse -Filter *.zip
          if (-not $zips) { throw "No solution ZIPs were produced by MSBuild. Check the MSBuild logs above." }
          Copy-Item $zips.FullName -Destination .\output\

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: timepicker-solution-zips
          path: output/*.zip
