name: Build PCF TimePicker Solution
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use Node 10 just for the PCF build to avoid "primordials" errors
      - name: Use Node 10.x for PCF build
        uses: actions/setup-node@v4
        with:
          node-version: '10.24.1'

      - name: Build PCF control
        shell: pwsh
        working-directory: TimePickerComponent
        run: |
          node -v
          npm -v
          npm ci
          npm run build

      # Install PAC as a .NET global tool (doesn't depend on Node 18)
      - name: Install Power Platform CLI (dotnet tool)
        shell: pwsh
        run: |
          dotnet --info
          dotnet tool install -g Microsoft.PowerApps.CLI.Tool
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          pac --version

      # Create a solution shell, add the PCF reference, and pack both zips
      - name: Create & pack solution
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path output -Force | Out-Null
          New-Item -ItemType Directory -Path WavsTimePicker.Sln -Force | Out-Null
          cd WavsTimePicker.Sln

          pac solution init --publisher-name WMATA --publisher-prefix wma --solution-name WavsTimePicker
          pac solution add-reference ..\TimePickerComponent\TimePickerComponent.pcfproj

          pac solution version --solution-name WavsTimePicker --solution-version 1.0.0.0
          pac solution pack --folder . --zipfile ..\output\WavsTimePicker.zip --packagetype Unmanaged
          pac solution pack --folder . --zipfile ..\output\WavsTimePicker_managed.zip --packagetype Managed

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: timepicker-solution-zips
          path: output/*.zip
