name: Build PCF TimePicker Solution
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Power Platform CLI
        run: npm install -g pac

      # Build the PCF control (repo root -> TimePickerComponent)
      - name: Build PCF control
        working-directory: TimePickerComponent
        run: |
          npm ci
          npm run build

      # Create solution and pack with PAC (no MSBuild, no cdsproj)
      - name: Create & pack solution
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path output -Force | Out-Null
          New-Item -ItemType Directory -Path WavsTimePicker.Sln -Force | Out-Null
          cd WavsTimePicker.Sln

          # init solution shell
          pac solution init --publisher-name WMATA --publisher-prefix wma --solution-name WavsTimePicker

          # add the PCF reference
          pac solution add-reference ..\TimePickerComponent\TimePickerComponent.pcfproj

          # optional: set a version
          pac solution version --solution-name WavsTimePicker --solution-version 1.0.0.0

          # pack unman
